

development:
  adapter: postgresql
  database: urbanchef_database_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: urbanchef_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: urbanchef_database_production
  pool: 5
  timeout: 5000
